### ISSUE TITLE
Failure to parse some valid Clojure names 

### ISSUE THREAD

**Issue by PEZ** [carocad/parcera#8]
The Clojure reader accepts this code:

```clojure
(defn ❤️ [x]
  (str "I ❤️ " x))

(❤️ "Clojure")
```

But Parcera (`0.1.2`) croaks on it.

These tests expose it:

```clojure
(deftest simple
  (testing "character literals"
    (as-> "\\t" input (is (= input (parcera/code (parcera/clojure input)))))
    (as-> "\\n" input (is (= input (parcera/code (parcera/clojure input)))))
    (as-> "\\r" input (is (= input (parcera/code (parcera/clojure input)))))
    (as-> "\\a" input (is (= input (parcera/code (parcera/clojure input)))))
    (as-> "\\é" input (is (= input (parcera/code (parcera/clojure input)))))
    (as-> "\\ö" input (is (= input (parcera/code (parcera/clojure input)))))
    (as-> "\\ï" input (is (= input (parcera/code (parcera/clojure input)))))
    (as-> "\\ϕ" input (is (= input (parcera/code (parcera/clojure input))))))
  
  (testing "names"
    (as-> "foo" input (is (= input (parcera/code (parcera/clojure input)))))
    (as-> "foo-bar" input (is (= input (parcera/code (parcera/clojure input)))))
    (as-> "foo->bar" input (is (= input (parcera/code (parcera/clojure input)))))
    (as-> "->" input (is (= input (parcera/code (parcera/clojure input)))))
    (as-> "->as" input (is (= input (parcera/code (parcera/clojure input)))))
    (as-> "föl" input (is (= input (parcera/code (parcera/clojure input)))))
    (as-> "Öl" input (is (= input (parcera/code (parcera/clojure input)))))
    (as-> "ϕ" input (is (= input (parcera/code (parcera/clojure input)))))
    (as-> "❤️" input (is (= input (parcera/code (parcera/clojure input)))))))
```

All but the ❤️ test pass. And that test errors like so:

```
ERROR in: parcera.test.core: core.cljc, line 52: simple: names:
  error: java.lang.IllegalArgumentException: No matching clause: [:index 0] + "
  expected: (= input (parcera/code (parcera/clojure input)))
```

**Comment by PEZ** [comment]
ClojureScript does not parse that code. Don't know how relevant for parcera, but anyway.

**Comment by carocad** [comment]
@PEZ thanks a lot for the info. Could you copy the error message of clojurescript over here ?

**Comment by PEZ** [comment]
Will do. Afk right now. I asked about it in the #clojure channel if the
Clojurians Slack. You might find the answers enlightening. 😎

**Comment by PEZ** [comment]
So this is what shadow-cljs says when trying to use an emoji in a name:

```
cljs.user=> (defn 😀[x] x)
:2
cljs.user.😀 = (function cljs$user$😀(x){
          ^^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at runInThisContext (vm.js:303:10)
    at global.SHADOW_NODE_EVAL (/Users/petery/Projects/calva-next/out/cljs-lib/cljs-lib.js:90:32)
    at Object.shadow$cljs$devtools$client$node$node_eval [as node_eval] (/Users/petery/Projects/calva-next/.shadow-cljs/builds/calva-lib/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:24:1)
    at /Users/petery/Projects/calva-next/.shadow-cljs/builds/calva-lib/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:49:13
    at Object.ret [as repl_call] (/Users/petery/Projects/calva-next/.shadow-cljs/builds/calva-lib/dev/out/cljs-runtime/shadow/cljs/devtools/client/env.cljs:104:11)
    at Object.shadow$cljs$devtools$client$node$repl_invoke [as repl_invoke] (/Users/petery/Projects/calva-next/.shadow-cljs/builds/calva-lib/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:47:1)
    at shadow$cljs$devtools$client$node$process_message (/Users/petery/Projects/calva-next/.shadow-cljs/builds/calva-lib/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:118:5)
    at /Users/petery/Projects/calva-next/.shadow-cljs/builds/calva-lib/dev/out/cljs-runtime/shadow/cljs/devtools/client/env.cljs:183:9
    at Object.shadow$cljs$devtools$client$env$process_next_BANG_ [as process_next_BANG_] (/Users/petery/Projects/calva-next/.shadow-cljs/builds/calva-lib/dev/out/cljs-runtime/shadow/cljs/devtools/client/env.cljs:171:7)
    at Object.shadow$cljs$devtools$client$env$process_ws_msg [as process_ws_msg] (/Users/petery/Projects/calva-next/.shadow-cljs/builds/calva-lib/dev/out/cljs-runtime/shadow/cljs/devtools/client/env.cljs:184:7)
    at WebSocket. (/Users/petery/Projects/calva-next/.shadow-cljs/builds/calva-lib/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:170:7)
    at WebSocket.emit (events.js:182:13)
    at Receiver.setSocket._receiver.onmessage (/Users/petery/Projects/calva-next/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/Users/petery/Projects/calva-next/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/Users/petery/Projects/calva-next/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/Users/petery/Projects/calva-next/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/Users/petery/Projects/calva-next/node_modules/ws/lib/Receiver.js:139:10)
    at Socket.setSocket._ultron.on (/Users/petery/Projects/calva-next/node_modules/ws/lib/WebSocket.js:138:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```
